routes/web.php
<?php

use App\Http\Controllers\EtiquetaCrudController;
use App\Http\Controllers\TareaCrudController;
use App\Http\Controllers\UsuarioCrudController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


    Route::view('/',"login")->name('login');

    Route::view('/inicio',"inicio")->middleware('inicio');
    Route::view('/login',"login")->name('login');
    Route::view('/registrar',"registrar")->name('registrar');


    Route::get('/Showregister', 'App\Http\Controllers\LoginController@showRegistrar')->name('register');
    Route::post('/registrar', 'App\Http\Controllers\LoginController@register')->name('registrar');
    Route::get('/inicio','App\Http\Controllers\LoginController@inicio')->name('inicio');

    Route::post('/validarLogin','App\Http\Controllers\LoginController@validarLogin');

    Route::post('/login', 'App\Http\Controllers\LoginController@login')->name('login.post');
    Route::get('/logout', 'App\Http\Controllers\LoginController@logout')->name('logout');

    Route::resource('tareas', TareaCrudController::class);
    Route::resource('etiquetas', EtiquetaCrudController::class);
    Route::resource('usuarios', UsuarioCrudController::class);

app/Models/Tarea.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tarea extends Model
{
    use HasFactory;
    protected $table = "tareas";
    protected $primarykey = "id";
    protected $fillable = ['nombre','id_usuario','descripcion',
    'fecha_creacion','fecha_vencimiento','created_at','updated_at'];
}

app/Http/Controllers/TareaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tarea;
use Illuminate\Http\Request;


/**
* @OA\Server(url="http://pttareas.test")
*/


class TareaController extends Controller
{
    /**
    * @OA\SecurityScheme(
    *     type="http",
    *     description="Autenticación JWT",
    *     name="Authorization",
    *     in="header",
    *     scheme="bearer",
    *     bearerFormat="JWT",
    *     securityScheme="bearerAuth"
    * )
    */

    //Controlador ruta Api

    /**
    * @OA\Get(
    *     path="/api/tareas",
    *       tags={"Tareas"},
    *       summary="Listado del registro de todas las tareas",
    *     @OA\Response(
    *         response=200,
    *         description="Mostrar todos los proyectos."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     ),
    *     security={
    *        {"bearerAuth": {}},
    *     },
    * )
    */

    public function index(){
        return Tarea::all();
    }

    /**
    * @OA\Get(
    *     path="/api/tareas/{id}",
    *       tags={"Tareas"},
    *       summary="Listado del registro de todas las tareas",
     *     @OA\Parameter(
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="string")
     *     ),
    *     @OA\Response(
    *         response=200,
    *         description="Mostrar todos los proyectos."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     ),
    *     security={
    *        {"bearerAuth": {}},
    *     },
    * )
    */
    public function show($id){
        return Tarea::find($id);
    }

 /**
    * @OA\Post(
    *     path="/api/tareas",
    *     tags={"Tareas"},
    *     summary="Crear tarea",
    *     @OA\RequestBody(
    *         @OA\JsonContent(
    *            @OA\Property(property="id", type="number"),
    *            @OA\Property(property="nombre", type="string"),
    *            @OA\Property(property="id_usuario", type="number"),
    *            @OA\Property(property="descripcion", type="string"),
    *            @OA\Property(property="fecha_creacion", type="string"),
    *            @OA\Property(property="fecha_vencimiento", type="string")
    *         )
    *     ),
    *     @OA\Response(
    *         response=201,
    *         description="Proyecto creado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function store(Request $request){
        Tarea::create($request->all());
    }

 /**
    * @OA\Put(
    *     path="/api/tareas/{id}",
    *     tags={"Tareas"},
    *     summary="Actualizar Tarea",
    *     @OA\RequestBody(
    *         @OA\JsonContent(
    *         @OA\Property(property="id", type="number"),
    *            @OA\Property(property="nombre", type="string"),
    *            @OA\Property(property="id_usuario", type="number"),
    *            @OA\Property(property="descripcion", type="string"),
    *            @OA\Property(property="fecha_creacion", type="string"),
    *            @OA\Property(property="fecha_vencimiento", type="string")
    *         )
    *     ),
    *     @OA\Response(
    *         response=202,
    *         description="Proyecto actualizado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function update(Request $request, $id){
        $tarea = Tarea::findOrFail($id);
        $tarea->update($request->all());
        return $tarea;
    }

    /**
    * @OA\Delete(
    *     path="/api/tareas/{id}",
    *     tags={"Tareas"},
    *     summary="Eliminar Tarea",
    *     @OA\Response(
    *         response=204,
    *         description="Proyecto eliminado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function delete($id){
        $tarea = Tarea::findOrFail($id);
        $tarea->delete();
        return 204;
    }
}

resources/views/tareas/create.blade.php
@extends('layouts.plantillabase')
 
@section('contenido')

<div class="container mt-2">
   
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left mb-2">
            <h2>Agregar tarea</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary "href="{{route('tareas.index')}}"> Regresar</a>
        </div>
    </div>
</div>
    
  @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
    </div>
  @endif
    
<form action="{{ route('tareas.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre tarea:</strong>
                <input type="text" name="nombre" class="form-control" placeholder="Nombre tarea">
               @error('nombre')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Usuario:</strong>
                <select name="id_usuario" id="id_usuario" class="form-control">
                    <option value=""></option>
                    @foreach ($usuarios as $usuario)
                    <option value="{{$usuario->id}}">{{$usuario->nombre}}</option>
                    @endforeach
                 </select>
                @error('usuario')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
            @enderror
            </div>
        </div>
 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Descripcion:</strong>
                 <input type="text" name="descripcion" class="form-control" placeholder="Descripcion">
                @error('descripcion')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Fecha creación:</strong>
                 <input type="datetime" name="fecha_creacion" class="form-control">
                @error('fecha_creacion')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Fecha Vencimiento:</strong>
                 <input type="date" name="fecha_vencimiento" class="form-control"
                 value="" min="2023-01-01" max="2023-12-31">
                @error('fecha_vencimiento')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        
        <div>
            <button type="submit" class="btn btn-primary mr-3">Enviar</button>
        </div>
    
</form>

@endsection

resources/views/tareas/edit.blade.php
@extends('layouts.plantillabase')
 
@section('contenido')

    <div class="container mt-2">

        <div class="row">
            <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Editar tarea</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('tareas.index') }}" enctype="multipart/form-data"> Regresar</a>
                    </div>
            </div>
        </div>
        
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif
    
        <form action="{{ route('tareas.update',$tarea->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            
            @error('render')
            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
           @enderror

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nombre tarea:</strong>
                        <input type="text" name="nombre" value="{{$tarea->nombre}}" class="form-control" placeholder="Nombre tarea">
                       @error('nombre')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                    </div>
                </div>
        
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Usuario:</strong>
                        <select name="id_usuario" id="id_usuario" class="form-control" value="{{$tarea->id_usuario}}">
                            <option></option>
                            @foreach ($usuarios as $usuario)
                            <option value="{{$usuario->id}}">{{$usuario->nombre}}</option>
                            @endforeach
                         </select>
                        @error('usuario')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                    </div>
                </div>
         
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Descripcion:</strong>
                         <input type="text" name="descripcion" class="form-control" value="{{$tarea->descripcion}}" placeholder="Descripcion">
                        @error('descripcion')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                    </div>
                </div>
        
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Fecha creación:</strong>
                         <input type="datetime" name="fecha_creacion" class="form-control" 
                         value="2023-09-11" min="2023-01-01" max="2023-12-31">
                        @error('fecha_creacion')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                    </div>
                </div>
        
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Fecha Vencimiento:</strong>
                         <input type="date" name="fecha_vencimiento" class="form-control"
                         value="2023-09-11" min="2023-01-01" max="2023-12-31">
                        @error('fecha_vencimiento')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                    </div>
                </div>

                
                @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
                @endif
                
                <div>
                    <button type="submit" class="btn btn-primary mr-3">Enviar</button>
                </div>

            </div>
        </form>
    </div>

@endsection

resources/views/tareas/index.blade.php
@extends('layouts.plantillabase')

@section('nav')

@endsection

@section('contenido')

    <div class="container mt-5">
        
    <div class="row">
            <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Tareas</h2>
                    </div>
                    <div class="pull-right mb-2">
                        <a class="btn btn-success" href="{{ route('tareas.create') }}">Crear tareas</a>
                    </div>
            </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    
    <table id="tareas" class="table table-bordered"  style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre Tarea</th>
                <th>Usuario</th>
                <th>descripcion</th>
                <th>fecha_creacion</th>
                <th>fecha_vencimiento</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($tareas as $tarea)
                <tr>
                    <td>{{ $tarea->id }}</td>
                    <td>{{ $tarea->nombre }}</td>
                    <td>{{ $tarea->id_usuario}}</td>
                    <td>{{ $tarea->descripcion }}</td>
                    <td>{{ $tarea->fecha_creacion }}</td>
                    <td>{{ $tarea->fecha_vencimiento }}</td>
                    <td>
                        <form action="{{ route('tareas.destroy',$tarea->id) }}" method="Post">
                            <a class="btn btn-primary" href="{{ route('tareas.edit',$tarea->id) }}">Editar</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="pull-right">
        <a class="btn btn-primary "href="{{route('inicio')}}">Regresar al inicio</a>
    </div>
@endsection