routes/web.php
<?php

use App\Http\Controllers\EtiquetaCrudController;
use App\Http\Controllers\TareaCrudController;
use App\Http\Controllers\UsuarioCrudController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


    Route::view('/',"login")->name('login');

    Route::view('/inicio',"inicio")->middleware('inicio');
    Route::view('/login',"login")->name('login');
    Route::view('/registrar',"registrar")->name('registrar');


    Route::get('/Showregister', 'App\Http\Controllers\LoginController@showRegistrar')->name('register');
    Route::post('/registrar', 'App\Http\Controllers\LoginController@register')->name('registrar');
    Route::get('/inicio','App\Http\Controllers\LoginController@inicio')->name('inicio');

    Route::post('/validarLogin','App\Http\Controllers\LoginController@validarLogin');

    Route::post('/login', 'App\Http\Controllers\LoginController@login')->name('login.post');
    Route::get('/logout', 'App\Http\Controllers\LoginController@logout')->name('logout');

    Route::resource('tareas', TareaCrudController::class);
    Route::resource('etiquetas', EtiquetaCrudController::class);
    Route::resource('usuarios', UsuarioCrudController::class);

app/Models/Etiqueta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Etiqueta extends Model
{
    use HasFactory;
    protected $table = "etiquetas";
    protected $primarykey = "id";
    protected $fillable = ['nombre','id_tarea','codigo','descripcion','created_at','updated_at'];
}

app/Http/Controllers/EtiquetaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Etiqueta;
use Illuminate\Http\Request;

/**
* @OA\Info(
*             title="API - Tareas",
*             version="1.0",
*             description="Listado de URI'S de la API tareas"
* )
*
* @OA\Server(url="http://pttareas.test")
*/

class EtiquetaController extends Controller
{
   /**
    * @OA\SecurityScheme(
    *     type="http",
    *     description="Autenticación JWT",
    *     name="Authorization",
    *     in="header",
    *     scheme="bearer",
    *     bearerFormat="JWT",
    *     securityScheme="bearerAuth"
    * )
    */


    // Controlador Ruta Api
    
    /**
    * @OA\Get(
    *     path="/api/etiquetas",
    *     tags={"Etiquetas"},
    *     summary="Listado del registro de todos las etiquetas",
    *     @OA\Response(
    *         response=200,
    *         description="Mostrar todos los proyectos."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     ),
    *     security={
    *        {"bearerAuth": {}},
    *     },
    * )
    */

    public function index(){
        return Etiqueta::all();
    }


    /**
    * @OA\Get(
    *     path="/api/etiquetas/{id}",
    *     tags={"Etiquetas"},
    *     summary="Listado del registro de todos las etiquetas",
    *     @OA\Parameter(
    *         in="path",
    *          name="id",
    *          required=true,
    *         @OA\Schema(type="string")
   *          ),
    *     @OA\Response(
    *         response=200,
    *         description="Mostrar todos los proyectos."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     ),
    *     security={
    *        {"bearerAuth": {}},
    *     },
    * )
    */

    public function show($id){
        return Etiqueta::find($id);
    }

    /**
    * @OA\Post(
    *     path="/api/etiquetas",
    *     tags={"Etiquetas"},
    *     summary="Crear etiqueta",
    *     @OA\RequestBody(
    *         @OA\JsonContent(
    *            @OA\Property(property="id", type="number"),
    *            @OA\Property(property="nombre", type="string"),
    *            @OA\Property(property="id_tarea", type="number"),
    *            @OA\Property(property="codigo", type="string"),
    *            @OA\Property(property="descripcion", type="string")
    *         )
    *     ),
    *     @OA\Response(
    *         response=201,
    *         description="Proyecto creado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function store(Request $request){
        Etiqueta::create($request->all());
    }
    /**
    * @OA\Put(
    *     path="/api/etiquetas/{id}",
    *     tags={"Etiquetas"},
    *     summary="Actualizar etiqueta",
    *     @OA\RequestBody(
    *         @OA\JsonContent(
    *         @OA\Property(property="id", type="number"),
    *         @OA\Property(property="nombre", type="string"),
    *         @OA\Property(property="id_tarea", type="number"),
    *         @OA\Property(property="codigo", type="string"),
    *         @OA\Property(property="descripcion", type="string")
    *         )
    *     ),
    *     @OA\Response(
    *         response=202,
    *         description="Proyecto actualizado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function update(Request $request, $id){
        $etiqueta = Etiqueta::findOrFail($id);
        $etiqueta->update($request->all());
        return $etiqueta;
    }
    /**
    * @OA\Delete(
    *     path="/api/etiquetas/{id}",
    *     tags={"Etiquetas"},
    *     summary="Eliminar etiqueta",
    *     @OA\Response(
    *         response=204,
    *         description="Proyecto eliminado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function delete($id){
        $etiqueta = Etiqueta::findOrFail($id);
        $etiqueta->delete();
        return 204;
    }
}

resources/views/etiquetas/create.blade.php
@extends('layouts.plantillabase')
 
@section('contenido')

<div class="container mt-2">
   
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left mb-2">
            <h2>Agregar Etiqueta</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary "href="{{route('etiquetas.index')}}"> Regresar</a>
        </div>
    </div>
</div>
    
  @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
    </div>
  @endif
    
<form action="{{ route('etiquetas.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre etiqueta:</strong>
                <input type="text" name="nombre" class="form-control" placeholder="Nombre etiqueta">
               @error('nombre')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Asignar tarea:</strong>
                <select name="id_tarea" id="id_tarea" class="form-control">
                    <option value=""></option>
                    @foreach ($tareas as $tarea)
                    <option value="{{$tarea->id}}">{{$tarea->nombre}}</option>
                    @endforeach
                 </select>
                @error('tarea')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
            @enderror
            </div>
        </div>
 
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Codigo:</strong>
                 <input type="text" name="codigo" class="form-control" placeholder="Descripcion">
                @error('codigo')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Descripcion:</strong>
                 <input type="text" name="descripcion" class="form-control" placeholder="Descripcion">
                @error('descripcion')
                  <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
               @enderror
            </div>
        </div>
        
        <div>
            <button type="submit" class="btn btn-primary mr-3">Enviar</button>
        </div>
    
</form>

@endsection

resources/views/etiquetas/edit.blade.php
@extends('layouts.plantillabase')
 
@section('contenido')

    <div class="container mt-2">

        <div class="row">
            <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Editar etiqueta</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('etiquetas.index') }}" enctype="multipart/form-data"> Regresar</a>
                    </div>
            </div>
        </div>
        
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif
    
        <form action="{{ route('etiquetas.update',$etiqueta->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nombre etiqueta:</strong>
                        <input type="text" name="nombre" class="form-control" value="{{$etiqueta->nombre}}" placeholder="Nombre etiqueta">
                       @error('nombre')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                    </div>
                </div>
        
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Asignar tarea:</strong>
                        <select name="id_tarea" id="id_tarea" class="form-control">
                            <option value=""></option>
                            @foreach ($tareas as $tarea)
                            <option value="{{$tarea->id}}">{{$tarea->nombre}}</option>
                            @endforeach
                         </select>
                        @error('tarea')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                    </div>
                </div>
         
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Codigo:</strong>
                         <input type="text" name="codigo" value="{{$etiqueta->codigo}}" class="form-control" placeholder="codigo">
                        @error('codigo')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                    </div>
                </div>
        
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Descripcion:</strong>
                         <input type="text" name="descripcion" value="{{$etiqueta->descripcion}}"  class="form-control" placeholder="Descripcion">
                        @error('descripcion')
                          <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                       @enderror
                    </div>
                </div>
                
                <div>
                    <button type="submit" class="btn btn-primary mr-3">Enviar</button>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/etiquetas/index.blade.php
@extends('layouts.plantillabase')

@section('nav')

@endsection

@section('contenido')

    <div class="container mt-5">
        
    <div class="row">
            <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Etiqueta</h2>
                    </div>
                    <div class="pull-right mb-2">
                        <a class="btn btn-success" href="{{ route('etiquetas.create') }}">Crear Etiqueta</a>
                    </div>
            </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    
    <table id="etiquetas" class="table table-bordered"  style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre etiqueta</th>
                <th>Cod tarea</th>
                <th>Codigo</th>
                <th>Descripcion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($etiquetas as $etiqueta)
                <tr>
                    <td>{{ $etiqueta->id }}</td>
                    <td>{{ $etiqueta->nombre }}</td>
                    <td>{{ $etiqueta->id_tarea }}</td>
                    <td>{{ $etiqueta->codigo }}</td>
                    <td>{{ $etiqueta->descripcion }}</td>
                    <td>
                        <form action="{{ route('etiquetas.destroy',$etiqueta->id) }}" method="Post">
                            <a class="btn btn-primary" href="{{ route('etiquetas.edit',$etiqueta->id) }}">Editar</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="pull-right">
        <a class="btn btn-primary "href="{{route('inicio')}}">Regresar al inicio</a>
    </div>
@endsection