routes/web.php
<?php

use App\Http\Controllers\EtiquetaCrudController;
use App\Http\Controllers\TareaCrudController;
use App\Http\Controllers\UsuarioCrudController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


    Route::view('/',"login")->name('login');

    Route::view('/inicio',"inicio")->middleware('inicio');
    Route::view('/login',"login")->name('login');
    Route::view('/registrar',"registrar")->name('registrar');


    Route::get('/Showregister', 'App\Http\Controllers\LoginController@showRegistrar')->name('register');
    Route::post('/registrar', 'App\Http\Controllers\LoginController@register')->name('registrar');
    Route::get('/inicio','App\Http\Controllers\LoginController@inicio')->name('inicio');

    Route::post('/validarLogin','App\Http\Controllers\LoginController@validarLogin');

    Route::post('/login', 'App\Http\Controllers\LoginController@login')->name('login.post');
    Route::get('/logout', 'App\Http\Controllers\LoginController@logout')->name('logout');

    Route::resource('tareas', TareaCrudController::class);
    Route::resource('etiquetas', EtiquetaCrudController::class);
    Route::resource('usuarios', UsuarioCrudController::class);

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    use HasFactory;
    protected $table = "usuarios";
    protected $primarykey = "id";
    protected $fillable = ['nombre','codigo','descripcion',
    'usuario','password_app','password','created_at','updated_at'];
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Usuario;
use Illuminate\Http\Request;

/**
* @OA\Server(url="http://pttareas.test")
*/

class UsuarioController extends Controller
{

/**
    * @OA\SecurityScheme(
    *     type="http",
    *     description="Autenticación JWT",
    *     name="Authorization",
    *     in="header",
    *     scheme="bearer",
    *     bearerFormat="JWT",
    *     securityScheme="bearerAuth"
    * )
    */

    // Controlador ruta Api

   // http://pttareas.test/api/documentation#/

     /**
    * @OA\Get(
    *     path="/api/usuarios",
    *       tags={"Usuarios"},
    *       summary="Listado del registro de todos los usuarios",
    *       security={ {"bearerAuth":{}}},
    *     @OA\Response(
    *         response=200,
    *         description="Mostrar todos los proyectos."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     ),
    * )
    */
    public function index(){
        return Usuario::all();
    }

    /**
    * @OA\Get(
    *     path="/api/usuarios/{id}",
    *       tags={"Usuarios"},
    *       summary="Listado un usuario",
     *      @OA\Parameter(
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="string")
     *     ),
    *     @OA\Response(
    *         response=200,
    *         description="Mostrar todos los proyectos."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     ),
    *     security={
    *        {"bearerAuth":{}},
    *     },
    * )
    */
    public function show($id){
        return Usuario::find($id);
    }

    /**
    * @OA\Post(
    *     path="/api/usuarios",
    *     tags={"Usuarios"},
    *     summary="Crear usuario",
    *     @OA\RequestBody(
    *         @OA\JsonContent(
    *            @OA\Property(property="id", type="number"),
    *            @OA\Property(property="nombre", type="string"),
    *            @OA\Property(property="codigo", type="string"),
    *            @OA\Property(property="descripcion", type="string"),
    *            @OA\Property(property="usuario", type="string")
    *         )
    *     ),
    *     @OA\Response(
    *         response=201,
    *         description="Proyecto creado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function store(Request $request){
        Usuario::create($request->all());
    }

    /**
    * @OA\Put(
    *     path="/api/usuarios{id}",
    *     tags={"Usuarios"},
    *     summary="Actualizar usuario",
    *     @OA\RequestBody(
    *         @OA\JsonContent(
    *            @OA\Property(property="id", type="number"),
    *            @OA\Property(property="nombre", type="string"),
    *            @OA\Property(property="codigo", type="string"),
    *            @OA\Property(property="descripcion", type="string"),
    *            @OA\Property(property="usuario", type="string")
    *         )
    *     ),
    *     @OA\Response(
    *         response=202,
    *         description="Proyecto creado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function update(Request $request, $id){
        $usuario = Usuario::findOrFail($id);
        $usuario->update($request->all());
        return $usuario;
    }

    /**
    * @OA\Delete(
    *     path="/api/usuarios/{id}",
    *     tags={"Usuarios"},
    *     summary="Eliminar usuario",
    *     @OA\Response(
    *         response=204,
    *         description="Proyecto eliminado satisfactoriamente."
    *     ),
    *     @OA\Response(
    *         response="default",
    *         description="Ha ocurrido un error."
    *     )
    * )
    */
    public function delete($id){
        $usuario = Usuario::findOrFail($id);
        $usuario->delete();
        return 204;
    }
}

resources/views/usuarios/create.blade.php
@extends('layouts.plantillabase')
 
@section('contenido')

    <div class="container mt-2">

        <div class="row">
            <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Crear usuario</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('usuarios.index') }}" enctype="multipart/form-data"> Regresar</a>
                    </div>
            </div>
        </div>
        
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif
    
        <form action="{{ route('usuarios.store')}}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row">

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nombre:</strong>
                        <input type="text" name="nombre" class="form-control" placeholder="nombre">
                        @error('nombre')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>identificacion:</strong>
                        <input type="text" name="codigo" class="form-control" placeholder="identificacion">
                        @error('codigo')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
               <div>
                <button type="submit" class="btn btn-primary mr-3">Enviar</button>
               </div>
            </div>
        </form>
    </div>

@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.plantillabase')
 
@section('contenido')

    <div class="container mt-2">

        <div class="row">
            <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Editar usuario</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('usuarios.index') }}" enctype="multipart/form-data"> Regresar</a>
                    </div>
            </div>
        </div>
        
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif
    
        <form action="{{ route('usuarios.update',$usuario->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            
            <div class="row">

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nombre:</strong>
                        <input type="text" name="nombre" value="{{ $usuario->nombre }}" class="form-control" placeholder="nombre">
                        @error('nombre')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Identificacion:</strong>
                        <input type="text" name="codigo" value="{{ $usuario->codigo }}" class="form-control" placeholder="identificacion">
                        @error('codigo')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
               <div>
                <button type="submit" class="btn btn-primary mr-3">Enviar</button>
               </div>
            </div>
        </form>
    </div>

@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.plantillabase')

@section('nav')

@endsection

@section('contenido')

    <div class="container mt-5">
        
    <div class="row">
            <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Usuarios</h2>
                    </div>
                    <div class="pull-right mb-2">
                        <a class="btn btn-success" href="{{ route('usuarios.create') }}">Crear usuarios</a>
                    </div>
            </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    
    <table id="usuario" class="table table-bordered"  style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Identifivcacion</th>
                <th>Usuario</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($usuarios as $usuario)
                <tr>
                    <td>{{ $usuario->id }}</td>
                    <td>{{ $usuario->nombre }}</td>
                    <td>{{ $usuario->codigo }}</td>
                    <td>{{ $usuario->usuario }}</td>
                    <td>
                        <form action="{{ route('usuarios.destroy',$usuario->id) }}" method="Post">
                            <a class="btn btn-primary" href="{{ route('usuarios.edit',$usuario->id) }}">Editar</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="pull-right">
        <a class="btn btn-primary "href="{{route('inicio')}}">Regresar al inicio</a>
    </div>
@endsection